<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Reservation extends Model
{
    protected $fillable = ['reserved_by', 'hotel_id', 'room_id', 'reserved_date', 'rate'];
    protected $guarded = ['transaction_id'];


    public function hotel()
    {
        return $this->belongsTo('App\Models\Hotel', 'hotel_id');
    }

    public function room()
    {
        return $this->belongsTo('App\Models\HotelRoom', 'room_id');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($item) {
            $year = now()->year;
            $count = 1;
            $last = Reservation::whereRaw("YEAR(created_at) = '". $year ."'")->where('reservation_id', '<>', null)->orderBy('id', 'desc')->first();
            if($last != null){
                $count = explode('-', $last->reservation_id)[1];
            }
            $item->reservation_id = $year."-".$count;
        });
    }

}
